# Generated by Django 3.0.5 on 2020-05-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_myproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myproducts',
            options={'verbose_name': 'My Product', 'verbose_name_plural': 'My Products'},
        ),
    ]
