# Generated by Django 3.0.5 on 2020-05-25 19:33

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200525_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/egonsaks/Documents/digital_marketplace/static_cdn/protected'), upload_to=products.models.download_media_location),
        ),
    ]
