# Generated by Django 3.0.5 on 2020-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200525_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_active',
            field=models.BooleanField(default=False),
        ),
    ]
