# Generated by Django 3.0.5 on 2020-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_sale_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sales_price',
            new_name='sale_price',
        ),
    ]
