# Generated by Django 3.0.5 on 2020-06-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200613_1624'),
        ('products', '0020_auto_20200615_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='sellers.SellerAccount'),
            preserve_default=False,
        ),
    ]
