# Generated by Django 3.0.5 on 2020-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='products',
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
