# Generated by Django 3.0.5 on 2020-06-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200630_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='product',
            new_name='products',
        ),
    ]
