# Generated by Django 3.0.5 on 2020-06-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selleraccount',
            options={'verbose_name': 'Seller Account', 'verbose_name_plural': 'Sellers Accounts'},
        ),
    ]
